name: Checks
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    - run: npx hardhat test
      env:
        # These are not needed for the tests but
        # hardhat fails to start if not present.
        NODE_TEST: "x"
        NODE_MAIN: "x"
        PRIVATE_KEY: "00000000000000000000000000000000000000000000000000"
        REPORT_GAS: "true"
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Solhint
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install -g solhint
      - run: make solhint
  Security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup env
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: |
          npm install
          sudo apt-get install python3-setuptools
      - name: Slither Static Analysis
        run: |
          git clone https://github.com/crytic/slither.git && cd slither && sudo python3 setup.py install
          make slither
      - name: Echidna Mutating testing
        run: |
          git clone https://github.com/crytic/echidna.git && cd echidna && sudo python3 setup.py install
          make echidna
        env:
          # These are not needed for the tests but
          # slither runs hardhat to compile the contracts and
          # hardhat compilation fails if these are not present.
          NODE_TEST: "x"
          NODE_MAIN: "x"
          PRIVATE_KEY: "00000000000000000000000000000000000000000000000000"
